module.exports = {
    'RECIPE_EN_GB': {
        "slime": "slime can be obtained by killing slime enemies.",
        "stone": "Stone is fairly common and can be mined from the ground in several areas of the map.",
        "sand": "Sand can be found in the desert biome or at the beach on the far left or right of the map.",
        "clay": "clay is found most commonly at the surface and is a slightly darker color than dirt.",
        "copper": "copper ore can be found on the surface, in the cavern biome, or underground and can be mined with any pickaxe.",
        "tin": "tin ore can be found on or near the surface, in the cavern biome or underground and can be mined with any pickaxe.",
        "iron": "iron can be found underground or in the cavern biome and can be mined with any pickaxe.",
        "wood": "Wood can be obtained by chopping down a tree with an axe.",
        "torch": "A torch can be crafted with one gel and one wood",
        "furnace": "A furnace can be crafted by using twenty stone blocks, four wood, and three torches",
        "iron anvil": "An iron anvil requires five iron bars and you need to stand near a work bench.",
        "iron pickaxe": "An iron pickaxe can be crafted by using three wood and 12 iron bars at any anvil.",
        "iron broadsword": "An iron broadsword can be crafted by using 8 iron bars at any anvil.",
        "work bench": "A work bench can be made with ten wood",
        "iron bar": "An iron bar can be made using the furnace to smelt three iron ore",
        "gold bar": "A gold bar can be made using the furnace to smelt three gold ore",
        "copper bar": "A copper bar can be made using the furnace to smelt three copper ore",
        "grey brick": "grey brick can be made by using 2 stone at a furnace.",
        "red brick": "red brick can be made by using 2 clay at a furnace.",
        "bottle": "A bottle can be made by using 1 glass block at a furnace",
        "tin bar": "A tin bar can be made using the furnace to smelt three tin ore",
    },
    'RECIPE_EN_US': {
        "slime": "slime can be obtained by killing slime enemies.",
        "stone": "Stone is fairly common and can be mined from the ground in several areas of the map.",
        "sand": "Sand can be found in the desert biome or at the beach on the far left or right of the map.",
        "clay": "clay is found most commonly at the surface and is a slightly darker color than dirt.",
        "copper": "copper ore can be found on the surface, in the cavern biome, or underground and can be mined with any pickaxe.",
        "tin": "tin ore can be found on or near the surface, in the cavern biome or underground and can be mined with any pickaxe.",
        "iron": "iron can be found underground or in the cavern biome and can be mined with any pickaxe.",
        "wood": "Wood can be obtained by chopping down a tree with an axe.",
        "torch": "A torch can be crafted with one gel and one wood",
        "furnace": "A furnace can be crafted by using twenty stone blocks, four wood, and three torches",
        "iron anvil": "An iron anvil requires five iron bars and you need to stand near a work bench.",
        "iron pickaxe": "An iron pickaxe can be crafted by using three wood and 12 iron bars at any anvil.",
        "iron broadsword": "An iron broadsword can be crafted by using 8 iron bars at any anvil.",
        "work bench": "A work bench can be made with ten wood",
        "iron bar": "An iron bar can be made using the furnace to smelt three iron ore",
        "gold bar": "A gold bar can be made using the furnace to smelt three gold ore",
        "copper bar": "A copper bar can be made using the furnace to smelt three copper ore",
        "grey brick": "grey brick can be made by using 2 stone at a furnace.",
        "red brick": "red brick can be made by using 2 clay at a furnace.",
        "bottle": "A bottle can be made by using 1 glass block at a furnace",
        "tin bar": "A tin bar can be made using the furnace to smelt three tin ore",
    },
};
